const menuData = [
  { id: 1, title: "Burger", img: "burger.jpg", price: "5.99" },
  { id: 2, title: "Pizza", img: "pizza.jpg", price: "8.99" },
  { id: 3, title: "Pasta", img: "pasta.jpg", price: "7.99" },
  { id: 4, title: "Salad", img: "salad.jpg", price: "4.99" },
  { id: 5, title: "Sushi", img: "sushi.jpg", price: "12.99" },
  { id: 6, title: "Taco", img: "taco.jpg", price: "3.99" },
  { id: 7, title: "Sandwich", img: "sandwich.jpg", price: "6.49" },
  { id: 8, title: "Steak", img: "steak.jpg", price: "14.99" },
  { id: 9, title: "Ramen", img: "ramen.jpg", price: "9.49" },
  { id: 10, title: "Ice Cream", img: "icecream.jpg", price: "3.99" },
  { id: 11, title: "Fries", img: "fries.jpg", price: "2.99" },
  { id: 12, title: "Hot Dog", img: "hotdog.jpg", price: "4.49" },
  { id: 13, title: "BBQ Ribs", img: "bbqribs.jpg", price: "15.99" },
  { id: 14, title: "Fried Chicken", img: "friedchicken.jpg", price: "7.99" },
  { id: 15, title: "Pancakes", img: "pancakes.jpg", price: "5.49" },
  { id: 16, title: "Waffles", img: "waffles.jpg", price: "6.49" },
  { id: 17, title: "Smoothie", img: "smoothie.jpg", price: "4.99" },
  { id: 18, title: "Coffee", img: "coffee.jpg", price: "2.99" },
  { id: 19, title: "Tea", img: "tea.jpg", price: "2.49" },
  { id: 20, title: "Muffin", img: "muffin.jpg", price: "3.49" },
  { id: 21, title: "Donut", img: "donut.jpg", price: "1.99" },
  { id: 22, title: "Cake", img: "cake.jpg", price: "4.99" },
  { id: 23, title: "Cupcake", img: "cupcake.jpg", price: "2.99" },
  { id: 24, title: "Burrito", img: "burrito.jpg", price: "7.49" },
  { id: 25, title: "Chips", img: "chips.jpg", price: "1.49" },
  { id: 26, title: "Popcorn", img: "popcorn.jpg", price: "2.99" },
  { id: 27, title: "Chicken Wings", img: "chickenwings.jpg", price: "9.99" },
  { id: 28, title: "Nachos", img: "nachos.jpg", price: "6.99" },
  { id: 29, title: "Quesadilla", img: "quesadilla.jpg", price: "5.99" },
  { id: 30, title: "Curry", img: "curry.jpg", price: "10.49" },
  { id: 31, title: "Soup", img: "soup.jpg", price: "4.49" },
  { id: 32, title: "Lasagna", img: "lasagna.jpg", price: "8.99" },
  { id: 33, title: "Grilled Cheese", img: "grilledcheese.jpg", price: "3.99" },
  { id: 34, title: "Fish & Chips", img: "fishchips.jpg", price: "11.49" },
  { id: 35, title: "Falafel", img: "falafel.jpg", price: "7.49" },
  { id: 36, title: "Gyro", img: "gyro.jpg", price: "6.99" },
  { id: 37, title: "Pad Thai", img: "padthai.jpg", price: "9.99" },
  { id: 38, title: "Gyoza", img: "gyoza.jpg", price: "5.49" },
  { id: 39, title: "Dim Sum", img: "dimsum.jpg", price: "8.49" },
  { id: 40, title: "Bruschetta", img: "bruschetta.jpg", price: "6.49" },
];

export default menuData;
